export const CHAT_EVENTS = {
  GET_ROOMS_LIST: 'GET_ROOMS_LIST',
  GET_ROOM: 'GET_ROOM',
};

export const CHAT_EMITS = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  CHANGE_ROOM: 'CHANGE_ROOM',
};

export const APP_EVENTS = {
  GET_MAIN_DATA: 'GET_MAIN_DATA',
};

export const USER_EVENTS = {
  GET_USER: 'GET_USER',
  UPDATE_USER_BALANCE: 'UPDATE_USER_BALANCE',
};

export const ROULETTE_EVENTS = {
  GET_ROULETTE_TIME: 'GET_ROULETTE_TIME',
  GET_ROULETTE_OPTIONS: 'GET_ROULETTE_OPTIONS',
  GET_WHEEL_DATA: 'GET_WHEEL_DATA',
};

export const BET_EVENTS = {
  GET_BETS_LIST: 'GET_BETS_LIST',
  GET_WIN_BET: 'GET_WIN_BET',
  ADD_BET: 'ADD_BET',
};
