module.exports = {
  GET_MAIN_DATA: "GET_MAIN_DATA",

  GET_ROOMS_LIST: "GET_ROOMS_LIST",
  GET_ROOM: "GET_ROOM",
  ADD_MESSAGE: "ADD_MESSAGE",
  CHANGE_ROOM: "CHANGE_ROOM",

  GET_ROULETTE_OPTIONS: "GET_ROULETTE_OPTIONS",
  GET_ROULETTE_TIME: "GET_ROULETTE_TIME",

  GET_BETS_LIST: "GET_BETS_LIST",
  GET_WIN_BET: "GET_WIN_BET",
  ADD_BET: "ADD_BET",

  GET_USER: "GET_USER",
  UPDATE_USER_BALANCE: "UPDATE_USER_BALANCE",

  GET_WHEEL_DATA: "GET_WHEEL_DATA"
};
